Cinema_project_MVC/Controllers/CategoryController.cs
using Cinema_project_MVC.Data;
using Cinema_project_MVC.Models;
using Cinema_project_MVC.Repository;
using Cinema_project_MVC.Repository.IReprsitory;
using Cinema_project_MVC.StaticData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cinema_project_MVC.Controllers
{
    [Authorize(Roles = $"{SD.AdminRole},{SD.CompanyRole}")]
    public class CategoryController : Controller
    {

        ICatrgoryRepository catrgoryRepository;
        public CategoryController(ICatrgoryRepository catrgoryRepository)
        {
            this.catrgoryRepository = catrgoryRepository;
        }

        public IActionResult Detailes(int Id)
        {


            var moves = catrgoryRepository.Getone(new Func<IQueryable<Category>, IQueryable<Category>>[]
            {
               q=>q.Include(p=>p.Movies).ThenInclude(p=>p.Cinema)
            },
            filter:e=>e.Id==Id


                );
            return View(moves);
        }

        public IActionResult Index()
        {

            var categorise= catrgoryRepository.GetAll(new Func<IQueryable<Category>, IQueryable<Category>>[]
            {
                 q=>q.Include(p=>p.Movies).ThenInclude(p=>p.Cinema)
            });
            return View(categorise.ToList());
        }
        public IActionResult Index2(int page, string? search)
        {

            var categorise = catrgoryRepository.GetAll(new Func<IQueryable<Category>, IQueryable<Category>>[]
            {
                
            });


            if(page <= 1)
                page = 1;
            int pageSize = 5;
            int totalProducts = catrgoryRepository.GetAll().Count();

            int totalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page;
            if (search != null)
            {
                search = search.TrimStart();
                search = search.TrimEnd();
                categorise = categorise.Where(e=>e.Name.Contains(search));
            }

            categorise= categorise.Skip((page-1)*5).Take(5);
            return View(categorise.ToList());
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Category category)
        {
            catrgoryRepository.Add(category);
            catrgoryRepository.Commit();

            return RedirectToAction("Index2");
        }

        public IActionResult Update(int Id)
        {
            var Category = catrgoryRepository.Getone(new Func<IQueryable<Category>, IQueryable<Category>>[]
           {
             
           },
           filter: e => e.Id == Id


               );
            return View(Category);
        }

           
        
        [HttpPost]
        public IActionResult Update(Category category)
        {
            catrgoryRepository.Edit(category);
            catrgoryRepository.Commit();

            return RedirectToAction("Index2");
        }

        [HttpPost]
        public IActionResult Delete(int Id)
        {
            var category = catrgoryRepository.Getone(new Func<IQueryable<Category>, IQueryable<Category>>[]
           {

           },
           filter: e => e.Id == Id


               );

            if (category != null)
            {
                catrgoryRepository.Delete(category);
                catrgoryRepository.Commit();
            }

            return RedirectToAction("Index2");
        }



    }
}

Cinema_project_MVC/Controllers/CinemaController.cs
using Cinema_project_MVC.Data;
using Cinema_project_MVC.Models;
using Cinema_project_MVC.Repository;
using Cinema_project_MVC.Repository.IReprsitory;
using Cinema_project_MVC.StaticData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cinema_project_MVC.Controllers
{
    [Authorize(Roles = $"{SD.AdminRole}")]
    public class CinemaController : Controller
    {

        ICenimaRepository CinemaRepository;
        public CinemaController(ICenimaRepository cinemaRepository)
        {
            CinemaRepository = cinemaRepository;
        }

        public IActionResult Index()
        {
            
            var cinemas = CinemaRepository.GetAll(new Func<IQueryable<Cinema>, IQueryable<Cinema>>[]
     {
                    q => q.Include(c => c.Movies)
                     .ThenInclude(p => p.Category)
     });

          
            return View(cinemas.ToList());
        }
        public IActionResult Detailes(int Id)
        {

            var moves = CinemaRepository.Getone(new Func<IQueryable<Cinema>, IQueryable<Cinema>>[]
            {
               q=>q.Include(p=>p.Movies)
               .ThenInclude(p=>p.Category)

            },
            filter: C => C.Id == Id
            );
            return View(moves);
        }
        public IActionResult Index2(int page, string? search)
        {

            var cinemas = CinemaRepository.GetAll(new Func<IQueryable<Cinema>, IQueryable<Cinema>>[]

     {
                    
     });

            if (page <= 1)
            {
                page = 1;
            }
            int pageSize = 5;
            int totalProducts = CinemaRepository.GetAll().Count();

            int totalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page;

            if (search != null)
            {
                cinemas = cinemas.Where(e => e.Name.Contains(search));
            }
              cinemas = cinemas.Skip((page - 1) * 5).Take(5);

            return View(cinemas.ToList());
        }
        public IActionResult Add()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Add(Cinema cinema)
        {
            CinemaRepository.Add(cinema);
            CinemaRepository.Commit();


            return RedirectToAction("Index2");
        }

        public IActionResult Edit(int Id)
        {
            var cinema= CinemaRepository.Getone(new Func<IQueryable<Cinema>, IQueryable<Cinema>>[]
            {

            },
            filter:e=>e.Id==Id
            
            
            );

            return View(cinema);
        }
        [HttpPost]
        public IActionResult Edit(Cinema cinema)
        {
            CinemaRepository.Edit
                (cinema);
            CinemaRepository.Commit();
            return RedirectToAction("Index2");

        }

     
        [HttpPost]
        public IActionResult Delete(int Id)
        {
            var category = CinemaRepository.Getone(new Func<IQueryable<Cinema>, IQueryable<Cinema>>[] { 
            
            }, 
            
            filter: e => e.Id == Id
            
            );

            if (category != null)
            {
                CinemaRepository.Delete(category);
                CinemaRepository.Commit();
            }

            return RedirectToAction("Index2");
        }



    }
}

Cinema_project_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema_project_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/Cinema_project_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/logo.png" class="img-fluid rounded-start" alt="..." style="height: 50px;>

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema_project_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Cinemas</a>
                        </li>

                        @if (User.IsInRole(SD.AdminRole) || User.IsInRole(SD.CompanyRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " data-bs-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">MangmentSystem</a>
                                <div class="dropdown-menu ">
                                    <a class="dropdown-item" href="/Category/Index2">Category</a>
                                    <a class="dropdown-item" href="/Actor/Index2">Actor</a>
                                    <a class="dropdown-item" href="/Cinema/Index2">Cinema</a>
                                    <a class="dropdown-item" href="/Movie/Index">Movies</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>

                <li class="nav-item mx-2">
                    <a class="nav-link text-dark" asp-area="" asp-controller="cart" asp-action="Index"> <i class="bi bi-cart3"></i></a>

                </li>
            </div>
            <form method="get" action="/Home/Index" class="mb-1 w-25 mx-auto mt-1">
                <div class="input-group">
                    <input type="text" name="searchTerm" class="form-control" placeholder="Search by movie name..." />
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </form>

            <ul class="navbar-nav   ">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Welcome @User.Identity.Name</a>
                        </li>

                    }

                    else
                    {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>

                    }


                </ul>
              
           
            
        </nav>
       

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Cinema_project_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>